"""add_course_registration_association

Revision ID: 1247423843bf
Revises: 2fe4df8dfdc8
Create Date: 2025-09-09 00:45:44.072008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1247423843bf'
down_revision = '2fe4df8dfdc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_registration',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_registration_course_id')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_course_registration_student_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_registration')
    # ### end Alembic commands ###
